version: 2
updates:

  # Maintain dependencies for maven
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "maven"
      include: "scope"
    labels:
      - "maven"
      - "dependencies"
    open-pull-requests-limit: 3
    pull-request-branch-name:
      separator: "-"
