name: ci-customer

on:
  push:
    paths:
      - 'pta-customer/**'
    tags:
      - 'pta-customer/v*.*.*'
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout latest code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
          cache-dependency-path: 'pta-customer/pom.xml'

      - name: Build with Maven
        run: mvn -B package --file pta-customer/pom.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Log in to the Container registry
        if: startsWith(github.ref, 'refs/tags/pta-customer/')
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        if: startsWith(github.ref, 'refs/tags/pta-customer/')
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: ${{ github.ref }}

      - name: Build and push Docker image
        if: startsWith(github.ref, 'refs/tags/pta-customer/')
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./pta-customer/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
