name: Build shopping

on:
  push:
    branches: [ "main" ]
    paths:
      - 'pta-shopping/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'pta-shopping/**'
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
        cache-dependency-path: 'pta-shopping/pom.xml'
    - name: Build with Maven
      run: mvn -B package --file pta-shopping/pom.xml
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
